# Generated by Django 3.1.2 on 2020-10-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='longitude',
        ),
    ]
