# Generated by Django 3.1.2 on 2020-10-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201019_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
